---
title: "Waterways Buffer"
author: "Craig O'Neill"
date: "May 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Libraries Needed

```{r}
library(tidyverse)
library(sf)
library(leaflet)
library(sp)
library(rgdal)
library(mapview)
```

##Load in KMZ (KML only at the moment)


```{r}
#Load the KML
location <- choose.files() #KML Only now

#Process the Layer Names and Numbers
layers <- st_layers(location)
lname <- layers$name


#Load all Layers in a ForLoop
datalist = list()
for(i in 1:NROW(lname)){
  dat <- st_read(location, layer = lname[i])
  dat$i <- i
  datalist[[i]] <- dat
}

#Combine All Layers into 1 SF File
mapfile <- do.call(rbind, datalist)

#View Map
mapview(mapfile)
```

##Load in the Most Recent Waterways Shapefiles

##Select the Counties your project is located in


```{r}
#Add Counties Project is located in
CACounties <- st_read("CA_Counties/CA_Counties_TIGER2016.shp")
CACounties <-st_transform(CACounties, "+init=epsg:4326")

#Set county of work.  Due to size of waterways, its best to only pick the one county where the work is occuring.
MBICounties <- subset(CACounties, NAME == "Madera")
#MBICounties <- subset(CACounties, NAME == "Kern" | NAME == "Fresno" | NAME == "Mariposa" | NAME == "Tulare" | NAME == "Kings" | NAME == "Madera" | NAME == "Merced")

```

##Filter Waterways Data down to County Level
```{r}
#CA Waterways Shapefiles
CAR <- st_read("CA_shapefile_wetlands/CA_shapefile_wetlands/CA_Riparian.shp") #CA_Riparian
colnames(CAR) <- c("Attribute", "Wetland_TY", "Acres", "Shape_Leng", "Shape_Area", "geometry")
CAR <- st_transform(CAR, "+init=epsg:4326")
CAR <- st_intersection(MBICounties, CAR)

CAWN <- st_read("CA_shapefile_wetlands/CA_shapefile_wetlands/CA_Wetlands_North.shp") #CA Wetlands North
colnames(CAWN) <- c("Attribute", "Wetland_TY", "Acres", "Shape_Leng", "Shape_Area", "geometry")
CAWN <- st_transform(CAWN, "+init=epsg:4326")
CAWN <- st_intersection(MBICounties, CAWN)

CAWNC <- st_read("CA_shapefile_wetlands/CA_shapefile_wetlands/CA_Wetlands_NorthCentral.shp") #CA Wetlands North Central
colnames(CAWNC) <- c("Attribute", "Wetland_TY", "Acres", "Shape_Leng", "Shape_Area", "geometry")
CAWNC <- st_transform(CAWNC, "+init=epsg:4326")
CAWNC <- st_intersection(MBICounties, CAWNC)

CAWS <- st_read("CA_shapefile_wetlands/CA_shapefile_wetlands/CA_Wetlands_South.shp") #CA Wetlands South
colnames(CAWS) <- c("Attribute", "Wetland_TY", "Acres", "Shape_Leng", "Shape_Area", "geometry")
CAWS <- st_transform(CAWS, "+init=epsg:4326")
CAWS <- st_intersection(MBICounties, CAWS)

CAWSC <- st_read("CA_shapefile_wetlands/CA_shapefile_wetlands/CA_Wetlands_SouthCentral.shp") #CA Wetlands South Central
colnames(CAWSC) <- c("Attribute", "Wetland_TY", "Acres", "Shape_Leng", "Shape_Area", "geometry")
CAWSC <- st_transform(CAWSC, "+init=epsg:4326")
CAWSC <- st_intersection(MBICounties, CAWSC)

CACA <- st_read("CA_shapefile_wetlands/CA_shapefile_wetlands/California.shp") #California
colnames(CACA) <- c("Attribute", "Wetland_TY", "Acres", "Shape_Leng", "Shape_Area", "geometry")
CACA <- st_transform(CACA, "+init=epsg:4326")
CACA <- st_intersection(MBICounties, CACA)

#Combine all
CAWater <- rbind(CAR, CAWN, CAWNC, CAWS, CAWSC, CACA)

#Project to the Google Earth KML file Datum
CAWater <- st_transform(CAWater, "+init=epsg:4326")

#Remove the SF data for the county.
CAWater <- CAWater %>% 
  filter(Wetland_TY != "CA")

```

##Calculate buffer around Worksite Locations

```{r}
#Buffer all site locations to 100ft
mapfile2 <- mapfile %>% 
  st_transform(3496) %>% #project to a format with units in feet
  st_buffer(dist = 100) %>%  #buffer by 100 feet around all locations
  st_transform(4326) #project back into the Google Earth WGS84 datum

#Remove the waterways data from the original KML (if still present)  The i number = folder number for the waterways.
mapfile2 <- mapfile2%>% 
  filter(i != 8) #16 just happens to be the layer number for the test file.  You'd need to look at the layers to figure out which is the waterways folder number.


```

##Calculate the areas of overlap

```{r}
#Find the areas where waterways intersect with the buffered project locations.
CropWater <- st_intersection(mapfile2, CAWater) %>% 
  select(-NAME) #remove redunant "NAME" dataset.  The all caps "NAME" is just the name of the county and is unneeded.  This is removed because when saving the KML it overwrites the location name with this NAME.

CropWater2 <- st_intersection(CAWater, mapfile2) %>% 
  select(-NAME)

mapview(CropWater2)+
  mapview(mapfile)+
  mapview(CropWater)
```

##Optional:  View Map of Project and Overlap Areas

```{r}
mapview(CropWater)+
  mapview(mapfile)+
  mapview(mapfile2)
```


##Save KML and Table of overlap areas

```{r}

#Write to file KML to file.
st_write(CropWater2, "current-2.kml", driver='kml', update = TRUE)

#Write Database to file for report write up.
CropTable <- CropWater2
st_geometry(CropTable) <- NULL
CropTable <- CropTable %>% 
  select(Name)

write.csv(CropTable[,1], "current-2.csv")

```



